-- Remove table if exists
drop table if exists bookmarks;

-- Create new table
create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    rating INTEGER NOT NULL
);

-- insert test data using multi-row insert statement
insert into bookmarks (title, url, description, rating)
values
    ('REI', 'https://www.rei.com/', 'gear', 5),
    ('Evo', 'https://www.evo.com/', 'more gear', 5),
    ('Reddit', 'https://www.reddit.com/', null, 3),
    ('Github', 'https://www.github.com/', 'programming n such', 3),
    ('Monkey Island Walkthrough', 'https://steamcommunity.com/sharedfiles/filedetails/?id=1357860328', 'spoiler alert', 5),
    ('Mountain Project', 'https://www.mountainproject.com/', 'climbs', 3),
    ('Crystal Mountain', 'https://www.crystalmountainresort.com/', 'official site', 3),
    ('NOAA Weather', 'https://forecast.weather.gov/', 'usually pretty accurate', 4),
    ('PostgreSQL Wikipedia entry', 'https://en.wikipedia.org/wiki/PostgreSQL', null, 4),
    ('Twitter', 'https://www.twitter.com/', 'nonsense', 4);